#CLASE 2: Conceptos básicos de algebra lineal

In [1]:
import numpy as np

##Vector de numeros enteros

In [2]:
from numpy import array
a=array([6.0,0,1,3,9,8])
print(a)

[6. 0. 1. 3. 9. 8.]


Una mejor forma de trabajar con librerias en Python

In [3]:
a = np.array([1,2,3])
print(type(a),a.shape,a[0],a[1],a[2])
a[0]=5 #actualiza valor del elemento con indice 0 de la matriz a
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b, b.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [5]:
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
1 2 4


In [6]:
a = np.zeros((1,7))
print(a)

[[0. 0. 0. 0. 0. 0. 0.]]


In [7]:
b = np.ones((3,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
c = np.full((2,5), 1252)
print(c)

[[1252 1252 1252 1252 1252]
 [1252 1252 1252 1252 1252]]


In [9]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
e = np.random.random((3,5))
print(e)

[[0.82148757 0.47906013 0.92362853 0.66936103 0.0114328 ]
 [0.28256888 0.13978607 0.01150259 0.15366689 0.30373794]
 [0.44162554 0.51111028 0.12215314 0.73118491 0.79917019]]


##Acceder a los elementos de un arreglo con numpy

In [11]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[1:3, 1:3]
print(b)

[[ 6  7]
 [10 11]]


In [12]:
print(a)
print(b)
print(a[0,1])
b[0,0]=77
print(a[0,1])
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7]
 [10 11]]
2
2
[[ 1  2  3  4]
 [ 5 77  7  8]
 [ 9 10 11 12]]
[[77  7]
 [10 11]]


In [14]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [15]:
row_r1= a[1, :]
row_r2= a[1:2, :]
row_r3= a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [16]:
col_c1= a[:, 1]
col_c2= a[:, 1:2]
print(col_c1, col_c1.shape)
print(col_c2, col_c2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
